import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/auth';
import { prisma } from '@/src/server/prisma';
import OpenAI from 'openai';
import { z } from 'zod';

const FlashcardsResponseSchema = z.object({
  flashcards: z.array(z.object({
    question: z.string(),
    answer: z.string()
  }))
});

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const session = await auth();
    if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { id } = await params;
    
    // Fetch the session and its summary
    const learningSession = await prisma.learningSession.findUnique({
      where: { id },
      select: { summary: true }
    });

    if (!learningSession || !learningSession.summary) {
      return NextResponse.json({ error: 'Session or summary not found' }, { status: 404 });
    }

    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    
    const prompt = `
      Jesteś ekspertem edukacyjnym. Poniżej znajduje się notatka z lekcji. 
      Na jej podstawie stwórz od 5 do 10 najważniejszych fiszek (pytanie i krótka odpowiedź) pozwalających utrwalić wiedzę z tej notatki.
      
      Zwróć wynik w formacie JSON z kluczem "flashcards", który jest tablicą obiektów z kluczami "question" i "answer".
      
      Notatka:
      ${learningSession.summary}
    `;

    const response = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: 'You are a helpful educational assistant that always outputs valid JSON.' },
        { role: 'user', content: prompt }
      ],
      response_format: { type: 'json_object' }
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
       throw new Error("No content generated by LLM");
    }

    const parsed = JSON.parse(content);
    return NextResponse.json(parsed);

  } catch (error: any) {
    console.error('Error generating flashcards:', error);
    return NextResponse.json({ error: 'Failed to generate flashcards' }, { status: 500 });
  }
}
